export const SKOPOS_CLI_HELP = `Skopos CLI

Usage:
  skopos adopt assess [target] [--actor <id>] [--dry-run] [--json]
  skopos adopt propose [target] --analysis <path> --actor <id> [--dry-run] [--json]
  skopos adopt approve [target] --proposal <digest> --actor <id> --reason <text> [--accept-material-risk] [--dry-run] [--json]
  skopos adopt verify [target] --execution <path> --actor <id> [--dry-run] [--json]
  skopos adopt activate [target] --actor <id> --reason <text> [--dry-run] [--json]
  skopos init [target] [--mode existing|greenfield] [--subtree <path>] [--actor <id>] [--dry-run] [--force] [--no-scaffold-instructions] [--force-instructions] [--json]
  skopos scan [target] [--subtree <path>] [--actor <id>] [--json]
  skopos session context [target] [--actor <id>] [--session-id <id>] [--host <name>] [--lease-seconds <n>] [--dry-run] [--json]
  skopos coordination status [target] [--json]
  skopos coordination session open [target] --actor <id> --host <name> [--session <id>] [--mode <writer|read-only|reviewer>] [--lease-seconds <n>] [--json]
  skopos coordination session heartbeat [target] --session <id> [--lease-seconds <n>] [--json]
  skopos coordination session close [target] --session <id> [--json]
  skopos coordination task reserve <task-id> [target] --session <id> [--json]
  skopos coordination task release <task-id> [target] --session <id> --reason <text> [--json]
  skopos coordination claim add <kind> <resource> [target] --task <id> --session <id> [--json]
  skopos start <goal> [target] [--scope <scope>] [--accept <criterion>] [--non-goal <text>] [--constraint <text>] [--own <path>] [--priority <0-100>] [--depends-on <task-id>] [--actor <id>] [--session-id <id>] [--host <name>] [--lease-seconds <n>] [--dry-run] [--json]
  skopos decide <question-id> <option-id> [target] [--actor <id>] [--dry-run] [--json]
  skopos discuss append-turn [target] [--thread <id>] [--session-id <id>] [--role <user|assistant|system>] [--source-event <event>] [--transcript-path <path>] [--message <text>|--message-stdin] [--dry-run] [--json]
  skopos discuss checkpoint [target] [--dry-run] [--json]
  skopos discuss handoff [target] [--dry-run] [--json]
  skopos discuss recent [target] [--json]
  skopos verify <task-id> [target] [--phase <admission|iteration|stabilization|closure>] [--dry-run] [--json]
  skopos readiness <task-id> [target] [--for <continue|integrate|close>] [--advance --actor <id>] [--dry-run] [--json]
  skopos work queue [target] [--actor <id>] [--dry-run] [--json]
  skopos work next [target] [--actor <id>] [--dry-run] [--json]
  skopos resolve [scope] [target] [--json]
  skopos context [scope] [target] [--json]
  skopos plan <goal> [target] [--scope <scope>] [--actor <id>] [--dry-run] [--json]
  skopos guards resolve [target] [--actor <id>] [--dry-run] [--json]
  skopos integrations propose [target] [--dry-run] [--json]
  skopos integrations approve [target] --proposal <digest> --accept <candidate-id> [--accept <candidate-id>...] --actor <id> --reason <text> [--dry-run] [--json]
  skopos integrations apply [target] --approval <digest> --actor <id> [--dry-run] [--json]
  skopos policies list [target] [--json]
  skopos policies show <pack> [target] [--json]
  skopos policies recommend [target] [--dry-run] [--json]
  skopos policies apply <pack> [target] --actor <id> --reason <text> [--dry-run] [--json]
  skopos policies drift [target] [--actor <id>] [--dry-run] [--json]
  skopos policies mappings list [target] [--json]
  skopos policies mappings confirm --pack <pack> --role <role> [--path <path>] --reason <text> --actor <id> [--cwd <target>] [--json]
  skopos policies mappings ignore --pack <pack> --role <role> --reason <text> --actor <id> [--cwd <target>] [--json]
  skopos policies mappings remove <decision-id> --actor <id> [--cwd <target>] [--json]
  skopos policies overrides list [target] [--json]
  skopos policies overrides add --reason <text> --actor <id> [--finding <id>|--rule <id>|--pack <id>|--source-path <path>] [--cwd <target>] [--json]
  skopos policies overrides remove <override-id> --actor <id> [--cwd <target>] [--json]
  skopos skills list [target] [--json]
  skopos skills show <pack> [target] [--json]
  skopos skills recommend [target] [--dry-run] [--json]
  skopos skills apply <pack> [target] --binding <id> --actor <id> --reason <text> [--dry-run] [--json]
  skopos actions list [target] [--json]
  skopos actions show <action> [target] [--json]
  skopos actions run <action> [target] [--task <id>] [--dry-run] [--approve] [--force] [--actor <id>] [--json]
  skopos evidence record-observation <task-id> [target] [--requirement <id>] [--guard <id>] --statement <text> --actor <id> [--dry-run] [--json]
  skopos task show <task-id> [target] [--json]
  skopos task claim <task-id> [target] --actor <id> [--json]
  skopos task release <task-id> [target] --actor <id> [--json]
  skopos task step complete <task-id> <step-id> [--cwd <target>] --actor <id> [--json]
  skopos task verify <task-id> [target] --actor <id> [--json]
  skopos knowledge [target] [--actor <id>] [--compact] [--summary] [--fields <names>] [--json]
  skopos impact [changed-path...] [--cwd <target>] [--actor <id>] [--json]
  skopos instructions scaffold [target] [--mode existing|greenfield] [--force] [--dry-run] [--actor <id>] [--json]
  skopos instructions sync [target] [--dry-run] [--actor <id>] [--json]
  skopos understand [target] [--actor <id>] [--dry-run] [--json]
  skopos ui render [target] [--output <path>] [--dry-run] [--json]
  skopos ui build [target] [--output-dir <path>] [--dry-run] [--json]
  skopos ui dev [target] [--host <host>] [--port <port>] [--json]        # live workspace UI with auto-refreshing state
  skopos ui serve [target] [--output-dir <path>] [--host <host>] [--port <port>] [--json]  # snapshot preview; restart after state changes
`;

export const printHelp = (): void => {
  process.stdout.write(SKOPOS_CLI_HELP);
};
