import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import { cn } from "@/lib/utils";
import { ClosingSection, PageAction, PageFrame, PageHero, PageSection, pageType } from "@/patterns/site/page-layout";
import { SiteShell } from "@/patterns/site/site-shell";
import { productWorkflowCopy } from "./content";

function WorkflowHeroVisual() {
  return <div className="workflow-hero-visual" role="img" aria-label="A developer request becomes a scoped Task, verified Evidence, and a continuation-ready handoff"><div className="workflow-visual-request"><span>YOUR REQUEST</span><strong>Make checkout recovery reliable.</strong><small>Do not change pricing or tax logic.</small></div><div className="workflow-visual-context"><span>MEMORY</span><span>SCOPE</span></div><div className="workflow-visual-task"><span>TASK</span><strong>Checkout recovery</strong><div><i /> Bounded</div></div><div className="workflow-visual-proof"><div><Icon symbol="fact_check" size="sm" /><span>EVIDENCE</span></div><strong>Ready to continue</strong></div><div className="workflow-visual-loop" aria-hidden="true"><Icon symbol="arrow_upward" size="sm" /><span>The project remembers</span></div></div>;
}

export function ProductWorkflowScreen() {
  return (
    <SiteShell><article className="bg-[var(--skopos-paper)]">
      <header><PageHero visual={<WorkflowHeroVisual />}><h1 className={pageType.hero}>{productWorkflowCopy.title}</h1><p className="mt-8 max-w-[680px] text-[clamp(1rem,1.3vw,1.2rem)] leading-[1.65] text-[var(--skopos-muted)]">{productWorkflowCopy.description}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a className="inline-flex min-h-[52px] items-center justify-between gap-7 border border-[var(--skopos-ink)] bg-[var(--skopos-ink)] px-[18px] text-[13px] font-bold text-white" href="#workflow">Follow the example<Icon symbol="arrow_downward" size="sm" /></a><PageAction href="/docs">Read the quickstart</PageAction></div></PageHero></header>

      <PageSection className="sticky top-[60px] z-10 border-y border-[var(--skopos-rule-light)] bg-[rgb(246_245_241/94%)] backdrop-blur md:top-16"><PageFrame><nav className="grid grid-cols-2 min-[760px]:grid-cols-4" aria-label="Workflow stages">{productWorkflowCopy.stages.map((stage) => <a key={stage.key} className="flex min-h-16 items-center gap-3 border-r border-b border-[var(--skopos-rule-light)] px-4 text-xs font-bold last:border-r-0 min-[760px]:border-b-0" href={`#${stage.key.toLowerCase()}`}><span className="font-mono text-[#777]">{stage.number}</span>{stage.key}</a>)}</nav></PageFrame></PageSection>

      <PageSection><PageFrame className="grid min-[900px]:grid-cols-2"><div className="px-[var(--page-gutter)] py-[clamp(56px,7vw,88px)] md:px-[clamp(38px,5vw,68px)]"><span className={cn(pageType.label, "text-[#777]")}>{productWorkflowCopy.example.label}</span><h2 id="workflow-example-title" className={cn(pageType.section, "mt-5")}>{productWorkflowCopy.example.title}</h2><p className="mt-5 text-[var(--skopos-muted)]">Watch one ordinary request move through the complete Skopos loop.</p></div><blockquote className="m-0 flex flex-col justify-between border-t border-[var(--skopos-rule-light)] p-[var(--page-gutter)] min-[900px]:border-t-0 min-[900px]:border-l min-[900px]:p-[clamp(38px,5vw,68px)]"><Icon symbol="format_quote" size="md" /><p className="my-8 text-[clamp(1.25rem,2.2vw,2rem)] leading-[1.35] font-medium">{productWorkflowCopy.example.prompt}</p><footer className="grid grid-cols-[auto_1fr] gap-x-5 gap-y-2 border-t border-[var(--skopos-rule-light)] pt-5 text-xs"><span className="text-[#777]">Repository</span><code>{productWorkflowCopy.example.repository}</code><span className="text-[#777]">Scope</span><code>{productWorkflowCopy.example.scope}</code></footer></blockquote></PageFrame></PageSection>

      <PageSection id="workflow" className="bg-[var(--skopos-night)] text-white" aria-label="The Skopos working loop"><PageFrame dark>{productWorkflowCopy.stages.map((stage) => <article key={stage.key} id={stage.key.toLowerCase()} className="grid border-b border-[var(--skopos-rule-dark)] last:border-b-0 min-[960px]:grid-cols-[130px_1fr_1fr]"><div className="px-[var(--page-gutter)] pt-12 font-mono text-[clamp(3rem,6vw,5.5rem)] leading-none font-light tracking-[-0.07em] text-[#333] min-[960px]:px-8 min-[960px]:py-[clamp(56px,6vw,82px)]">{stage.number}</div><div className="px-[var(--page-gutter)] py-10 min-[960px]:border-l min-[960px]:border-[var(--skopos-rule-dark)] min-[960px]:px-[clamp(30px,4vw,54px)] min-[960px]:py-[clamp(56px,6vw,82px)]"><Icon symbol={stage.icon} size="md" /><span className={cn(pageType.label, "mt-7 block text-[#888]")}>{stage.key}</span><h2 className={cn(pageType.section, "mt-5")}>{stage.summary}</h2><div className="mt-8 border-t border-[var(--skopos-rule-dark)] pt-5"><span className={cn(pageType.label, "text-[#888]")}>What you say</span><blockquote className="mt-3 text-lg leading-[1.5]">“{stage.whatYouSay}”</blockquote></div></div><div className="border-t border-[var(--skopos-rule-dark)] px-[var(--page-gutter)] py-10 min-[960px]:border-t-0 min-[960px]:border-l min-[960px]:px-[clamp(30px,4vw,54px)] min-[960px]:py-[clamp(56px,6vw,82px)]"><span className={cn(pageType.label, "text-[#888]")}>What Skopos handles</span><h3 className={cn(pageType.card, "mt-6")}>{stage.handledTitle}</h3><p className="mt-4 leading-[1.6] text-[var(--skopos-night-muted)]">{stage.handledDescription}</p><ul className="mt-7 grid list-none gap-3 p-0">{stage.details.map(detail => <li key={detail} className="flex gap-3 text-sm text-[#d0d0d0]"><Icon symbol="check" size="sm" />{detail}</li>)}</ul></div></article>)}</PageFrame></PageSection>

      <PageSection><PageFrame><div className="px-[var(--page-gutter)] py-[clamp(56px,7vw,88px)] md:px-[clamp(38px,5vw,68px)]"><span className={cn(pageType.label, "text-[#777]")}>The result</span><h2 id="workflow-outcome-title" className={cn(pageType.section, "mt-5 max-w-[920px]")}>The code changed. The project can explain what happened.</h2></div><div className="grid border-t border-[var(--skopos-rule-light)] md:grid-cols-3">{productWorkflowCopy.outcome.map((item,index) => <article key={item.label} className="border-b border-[var(--skopos-rule-light)] p-[var(--page-gutter)] last:border-b-0 md:border-r md:border-b-0 md:p-[clamp(28px,4vw,48px)] md:last:border-r-0"><span className="font-mono text-xs text-[#777]">{String(index+1).padStart(2,"0")}</span><h3 className={cn(pageType.card,"mt-8")}>{item.label}</h3><p className="mt-4 leading-[1.6] text-[var(--skopos-muted)]">{item.value}</p></article>)}</div></PageFrame></PageSection>

      <ClosingSection title="Talk naturally. Let the project carry the important parts." description="Start with one real repository and one outcome you want your coding agent to finish well."><PageAction href="/docs" primary light>Follow the first workflow</PageAction><PageAction href="/project-memory" light>Understand Project Memory</PageAction></ClosingSection>
    </article></SiteShell>
  );
}
