import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import { SiteShell } from "@/patterns/site/site-shell";
import { cn } from "@/lib/utils";
import { agentWorkItems } from "./agent-work-content";
import { DocumentationFrame, DocumentationGrid, DocumentationKicker, DocumentationSection, documentationType } from "./documentation-layout";

export function AgentWorkScreen() {
  return <SiteShell><article className="bg-[var(--skopos-paper)]">
    <header><DocumentationSection><DocumentationFrame className="grid min-h-[clamp(620px,calc(100vh-64px),790px)] min-[901px]:grid-cols-[1.1fr_0.9fr]"><div className="flex flex-col items-start justify-center px-[var(--page-gutter)] py-[clamp(70px,8vw,112px)] md:px-[clamp(38px,5vw,68px)]"><Link className="quickstart-back" href="/docs"><Icon symbol="arrow_back" size="sm" />Documentation</Link><h1 className={cn(documentationType.hero, "mt-9 max-w-[850px]")}>Work with your coding agent. Keep the project in control.</h1><p className="mt-[30px] max-w-[680px] text-[17px] leading-[1.65] text-[var(--skopos-muted)]">Say what you want in normal language. Skopos gives the conversation reliable project context, a real work boundary, approved actions, proof, and a path into the next Session.</p></div><DocumentationGrid className="flex min-h-[420px] flex-col justify-center border-t border-[var(--skopos-rule-light)] px-[var(--page-gutter)] py-[clamp(52px,6vw,82px)] min-[901px]:min-h-0 min-[901px]:border-t-0 min-[901px]:border-l md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>THE SIMPLE MODEL</DocumentationKicker>{["You discuss and decide.", "Your agent reasons and writes code.", "Skopos keeps the project coherent."].map((line) => <strong key={line} className="border-b border-[var(--skopos-rule-light)] py-[27px] text-[clamp(1.55rem,2.25vw,2.25rem)] leading-[1.05] tracking-[-0.045em]">{line}</strong>)}</DocumentationGrid></DocumentationFrame></DocumentationSection></header>
    <DocumentationSection aria-labelledby="agent-work-list-title"><DocumentationFrame className="py-[clamp(72px,8vw,112px)]"><header className="px-[var(--page-gutter)] pb-[clamp(52px,6vw,76px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>EVERYDAY WORK</DocumentationKicker><h2 id="agent-work-list-title" className={cn(documentationType.section, "mt-[25px] max-w-[850px]")}>Start with what you want to accomplish.</h2><p className="mt-[22px] max-w-[690px] leading-[1.65] text-[var(--skopos-muted)]">Each path shows a natural prompt and the project responsibility Skopos keeps stable behind it.</p></header><div className="grid border-t border-[var(--skopos-rule-light)] md:grid-cols-2">{agentWorkItems.map((item, index) => <article key={item.number} className={cn("flex min-w-0 flex-col border-b border-[var(--skopos-rule-light)] p-[clamp(34px,4vw,52px)]", index % 2 === 0 && "md:border-r", index >= agentWorkItems.length - 2 && "md:border-b-0", index === agentWorkItems.length - 1 && "border-b-0")}><span className="font-mono text-[10px] text-[#787878]">{item.number}</span><h3 className="mt-[30px] max-w-[550px] text-[clamp(1.8rem,2.55vw,2.65rem)] leading-none tracking-[-0.05em]">{item.title}</h3><p className="mt-5 max-w-[570px] leading-[1.6] text-[var(--skopos-muted)]">{item.description}</p><blockquote className="mt-[30px] flex-1 border-y border-[var(--skopos-rule-light)] py-6 text-base leading-[1.5] font-semibold">“{item.prompt}”</blockquote><div className="pt-[22px]"><small className="font-mono text-[9px] tracking-[0.1em] text-[#7b7b7b]">SKOPOS HANDLES</small><p className="mt-2.5 text-[13px] leading-[1.55] text-[var(--skopos-muted)]">{item.handles}</p></div><Link className="mt-7 flex items-center justify-between gap-5 border-t border-[var(--skopos-rule-light)] pt-[22px] text-[13px] font-bold" href={item.href}>{item.action}<Icon symbol="arrow_forward" size="sm" /></Link></article>)}</div></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white"><DocumentationFrame dark className="grid min-[901px]:grid-cols-[0.9fr_1.1fr]"><div className="px-[var(--page-gutter)] py-[clamp(68px,7vw,100px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker className="text-[#747474]">THE BOUNDARY</DocumentationKicker><h2 className={cn(documentationType.section, "mt-[25px]")}>Skopos supports the conversation. It does not replace it.</h2></div><ul className="m-0 flex list-none flex-col justify-center border-t border-[var(--skopos-rule-dark)] p-0 min-[901px]:border-t-0 min-[901px]:border-l">{["Your coding agent still owns general reasoning and implementation.", "You still approve decisions that change direction, risk, or public behavior.", "Skopos protects project truth, Task intent, enforcement, recovery, and Evidence."].map((item, index) => <li key={item} className={cn("grid min-h-[100px] grid-cols-[30px_1fr] items-center gap-4 border-b border-[var(--skopos-rule-dark)] px-[34px] py-5 leading-[1.55] text-[#d0d0d0]", index === 2 && "border-b-0")}><Icon symbol="check_circle" size="sm" />{item}</li>)}</ul></DocumentationFrame></DocumentationSection>
  </article></SiteShell>;
}
