import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import { cn } from "@/lib/utils";
import { SiteShell } from "@/patterns/site/site-shell";
import { DocumentationCopyBlock } from "./copy-block";
import type { CustomizeGuide } from "./customize-content";
import { DocumentationBackLink, DocumentationFrame, DocumentationKicker, DocumentationSection, DocumentationSectionHeading, documentationType } from "./documentation-layout";

export function CustomizeGuideScreen({ guide }: { guide: CustomizeGuide }) {
  return <SiteShell><article className="bg-[var(--skopos-paper)]">
    <header><DocumentationSection><DocumentationFrame className="grid min-h-[clamp(590px,calc(100vh-64px),760px)] min-[901px]:grid-cols-[1.08fr_0.92fr]"><div className="flex flex-col items-start justify-center px-[var(--page-gutter)] py-[clamp(70px,8vw,112px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationBackLink href="/docs/customize">Customize Skopos</DocumentationBackLink><DocumentationKicker className="mt-8">{guide.number} · {guide.label}</DocumentationKicker><h1 className={cn(documentationType.hero, "mt-7 max-w-[780px]")}>{guide.title}</h1></div><div className="flex flex-col justify-center border-t border-[var(--skopos-rule-light)] px-[var(--page-gutter)] py-[clamp(58px,7vw,90px)] min-[901px]:border-t-0 min-[901px]:border-l md:px-[clamp(38px,5vw,68px)]"><p className="text-lg leading-[1.65] text-[var(--skopos-muted)]">{guide.description}</p><strong className="mt-8 border-t border-[var(--skopos-rule-light)] pt-8 text-[clamp(1.6rem,2.4vw,2.4rem)] leading-[1.1] tracking-[-0.045em]">{guide.promise}</strong></div></DocumentationFrame></DocumentationSection></header>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white" aria-label="Prompt example"><DocumentationFrame dark className="grid min-[901px]:grid-cols-[0.9fr_1.1fr]"><div className="flex flex-col justify-center px-[var(--page-gutter)] py-[clamp(64px,7vw,96px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>Start with a conversation</DocumentationKicker><h2 className={cn(documentationType.section, "mt-6")}>Tell your agent the outcome and the safety boundary.</h2><p className="mt-5 leading-[1.65] text-[var(--skopos-night-muted)]">Skopos can help translate the request into its technical model after the intent is clear.</p></div><div className="border-t border-[var(--skopos-rule-dark)] p-[var(--page-gutter)] min-[901px]:border-t-0 min-[901px]:border-l md:p-[clamp(38px,5vw,68px)]"><DocumentationCopyBlock label="Say this to your agent" value={guide.prompt} kind="prompt" /></div></DocumentationFrame></DocumentationSection>
    <DocumentationSection aria-labelledby="customize-guide-process-title"><DocumentationFrame className="py-[clamp(70px,8vw,112px)]"><DocumentationSectionHeading number="HOW IT WORKS" id="customize-guide-process-title" title="A reviewed path from intent to project behavior." /><ol className="m-0 grid list-none border-t border-[var(--skopos-rule-light)] p-0 md:grid-cols-3">{guide.steps.map((step, index) => <li key={step.title} className={cn("min-h-[300px] border-b border-[var(--skopos-rule-light)] p-[clamp(32px,4vw,48px)] md:border-r md:border-b-0", index === guide.steps.length - 1 && "border-b-0 md:border-r-0")}><span className="font-mono text-[10px] text-[#777]">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-12 text-[clamp(1.8rem,2.5vw,2.55rem)] leading-none tracking-[-0.05em]">{step.title}</h3><p className="mt-5 leading-[1.6] text-[var(--skopos-muted)]">{step.description}</p></li>)}</ol></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="border-t border-[var(--skopos-rule-light)]" aria-labelledby="customize-guide-examples-title"><DocumentationFrame className="grid min-[901px]:grid-cols-[0.8fr_1.2fr]"><div className="px-[var(--page-gutter)] py-[clamp(64px,7vw,96px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>USE IT FOR</DocumentationKicker><h2 id="customize-guide-examples-title" className={cn(documentationType.section, "mt-6")}>Common project uses.</h2></div><ul className="m-0 flex list-none flex-col justify-center border-t border-[var(--skopos-rule-light)] p-0 min-[901px]:border-t-0 min-[901px]:border-l">{guide.examples.map((example, index) => <li key={example} className={cn("grid min-h-[82px] grid-cols-[26px_1fr] items-center gap-4 border-b border-[var(--skopos-rule-light)] px-8 py-4 text-sm", index === guide.examples.length - 1 && "border-b-0")}><Icon symbol="check" size="sm" />{example}</li>)}</ul></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="border-t border-[var(--skopos-rule-light)]" aria-labelledby="customize-guide-terms-title"><DocumentationFrame className="py-[clamp(70px,8vw,112px)]"><DocumentationSectionHeading number="UNDER THE HOOD" id="customize-guide-terms-title" title="The Skopos names for what you just configured." /><dl className="m-0 grid border-t border-[var(--skopos-rule-light)] md:grid-cols-3">{guide.terms.map((item, index) => <div key={item.term} className={cn("min-h-[230px] border-b border-[var(--skopos-rule-light)] p-[clamp(30px,4vw,46px)] md:border-r md:border-b-0", index === guide.terms.length - 1 && "border-b-0 md:border-r-0")}><dt className="text-[clamp(1.6rem,2.3vw,2.2rem)] font-bold tracking-[-0.04em]">{item.term}</dt><dd className="mt-5 leading-[1.6] text-[var(--skopos-muted)]">{item.meaning}</dd></div>)}</dl></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white"><DocumentationFrame dark className="grid items-center gap-8 px-[var(--page-gutter)] py-[clamp(52px,6vw,78px)] md:grid-cols-[90px_1fr] md:px-[clamp(38px,5vw,68px)]"><Icon symbol="shield" size="xl" /><div><DocumentationKicker>WHAT THIS CANNOT DO</DocumentationKicker><p className="mt-5 max-w-[900px] text-lg leading-[1.65] text-[var(--skopos-night-muted)]">{guide.boundary}</p></div></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white"><DocumentationFrame dark className="flex min-h-[290px] flex-col items-start justify-between gap-12 border-t px-[var(--page-gutter)] py-[clamp(52px,6vw,76px)] min-[901px]:flex-row min-[901px]:items-center md:px-[clamp(38px,5vw,68px)]"><div><DocumentationKicker>NEXT</DocumentationKicker><h2 className={cn(documentationType.section, "mt-6")}>Keep adapting Skopos to the project.</h2></div><Link className="flex min-h-[58px] w-full items-center justify-between gap-5 bg-white px-5 text-[13px] font-bold text-[var(--skopos-ink)] min-[901px]:w-auto min-[901px]:min-w-[280px]" href={guide.next.href}>{guide.next.label}<Icon symbol="arrow_forward" size="sm" /></Link></DocumentationFrame></DocumentationSection>
  </article></SiteShell>;
}
