import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import { cn } from "@/lib/utils";
import { SiteShell } from "@/patterns/site/site-shell";
import { checkoutCustomizeExample, customizeGuides } from "./customize-content";
import { DocumentationBackLink, DocumentationFrame, DocumentationKicker, DocumentationSection, DocumentationSectionHeading, documentationType } from "./documentation-layout";

const guideIcon = (slug: string) => slug === "connect-tools" ? "terminal" : slug === "project-rules" ? "verified_user" : slug === "expert-guidance" ? "psychology" : slug === "coding-agents" ? "smart_toy" : "cloud_sync";

export function CustomizeOverviewScreen() {
  return <SiteShell><article className="bg-[var(--skopos-paper)]">
    <header><DocumentationSection><DocumentationFrame className="grid min-h-[clamp(600px,calc(100vh-64px),780px)] min-[901px]:grid-cols-[1.08fr_0.92fr]"><div className="flex flex-col items-start justify-center px-[var(--page-gutter)] py-[clamp(70px,8vw,112px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationBackLink href="/docs">Documentation</DocumentationBackLink><h1 className={cn(documentationType.hero, "mt-9 max-w-[800px]")}>Skopos works the way your project works.</h1></div><div className="flex flex-col items-start justify-center border-t border-[var(--skopos-rule-light)] px-[var(--page-gutter)] py-[clamp(58px,7vw,90px)] min-[901px]:border-t-0 min-[901px]:border-l md:px-[clamp(38px,5vw,68px)]"><p className="text-[clamp(1.5rem,2.5vw,2.45rem)] leading-[1.25] tracking-[-0.04em] text-[var(--skopos-muted)]">Show it where project knowledge lives, which tools are trusted, what rules matter, and which coding agents you use.</p><Link className="mt-10 flex min-h-14 w-full items-center justify-between bg-[var(--skopos-ink)] px-5 text-[13px] font-bold text-white" href="/docs/customize/connect-tools">Start with your project tools<Icon symbol="arrow_forward" size="sm" /></Link></div></DocumentationFrame></DocumentationSection></header>
    <DocumentationSection aria-labelledby="customize-paths-title"><DocumentationFrame className="py-[clamp(70px,8vw,112px)]"><DocumentationSectionHeading number="01" id="customize-paths-title" title="Start with what you want Skopos to understand." description="You do not need to learn the internal model first. Choose the part of your project you want agents to use more reliably." /><div className="grid border-t border-[var(--skopos-rule-light)] md:grid-cols-2 min-[1100px]:grid-cols-5">{customizeGuides.map((guide, index) => <Link key={guide.slug} className={cn("grid min-h-[280px] grid-cols-[1fr_auto] content-start border-r border-b border-[var(--skopos-rule-light)] p-[clamp(26px,3vw,38px)]", index % 2 === 1 && "max-[1099px]:md:border-r-0", index >= 4 && "border-b-0", index === 4 && "border-r-0")} href={`/docs/customize/${guide.slug}`}><span className="font-mono text-[10px] text-[#777]">{guide.number}</span><Icon symbol={guideIcon(guide.slug)} size="lg" /><strong className="col-span-2 mt-12 text-[clamp(1.45rem,2vw,2rem)] leading-none tracking-[-0.04em]">{guide.label}</strong><p className="col-span-2 mt-4 text-sm leading-[1.55] text-[var(--skopos-muted)]">{guide.description}</p><Icon className="col-start-2 mt-6 justify-self-end" symbol="arrow_forward" size="sm" /></Link>)}</div></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white" aria-labelledby="customize-example-title"><DocumentationFrame dark className="grid min-[901px]:grid-cols-[0.9fr_1.1fr]"><div className="px-[var(--page-gutter)] py-[clamp(68px,7vw,100px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>02 · A real request</DocumentationKicker><h2 id="customize-example-title" className={cn(documentationType.section, "mt-6")}>“Make checkout recover safely when the connection drops.”</h2><p className="mt-6 leading-[1.65] text-[var(--skopos-night-muted)]">The developer states the outcome. Skopos combines remembered project truth with the tools and protections this repository has chosen.</p></div><ol className="m-0 grid list-none border-t border-[var(--skopos-rule-dark)] p-0 sm:grid-cols-2 min-[901px]:border-t-0 min-[901px]:border-l">{checkoutCustomizeExample.map((step, index) => <li key={step.label} className={cn("min-h-[180px] border-r border-b border-[var(--skopos-rule-dark)] p-7", index % 2 === 1 && "border-r-0", index >= 4 && "border-b-0")}><span className="font-mono text-[9px] text-[#888]">{String(index + 1).padStart(2, "0")}</span><strong className="mt-7 block">{step.label}</strong><p className="mt-3 text-[13px] leading-[1.55] text-[var(--skopos-night-muted)]">{step.value}</p></li>)}</ol></DocumentationFrame></DocumentationSection>
    <DocumentationSection aria-labelledby="customize-language-title"><DocumentationFrame className="py-[clamp(70px,8vw,112px)]"><DocumentationSectionHeading number="03" id="customize-language-title" title="Learn the name after you understand the job." description="The documentation introduces technical vocabulary only when it gives you more control." /><div className="grid border-t border-[var(--skopos-rule-light)] md:grid-cols-2">{[["Your tools", "Actions", "Approved ways to test, build, generate, inspect, or operate."], ["Your rules", "Guards and Policies", "Deterministic requirements and accepted project standards."], ["Your expertise", "Skills", "Focused guidance selected for a relevant Task."], ["Your agents", "Host adapters and MCP", "Different agent environments using the same Skopos authority."]].map(([plain, technical, meaning], index) => <article key={plain} className={cn("grid min-h-[230px] grid-cols-[1fr_auto] border-r border-b border-[var(--skopos-rule-light)] p-[clamp(30px,4vw,46px)]", index % 2 === 1 && "border-r-0", index >= 2 && "border-b-0")}><span className="text-sm text-[var(--skopos-muted)]">{plain}</span><Icon symbol="arrow_forward" size="sm" /><strong className="col-span-2 mt-10 text-[clamp(1.7rem,2.4vw,2.35rem)] tracking-[-0.045em]">{technical}</strong><p className="col-span-2 mt-4 leading-[1.55] text-[var(--skopos-muted)]">{meaning}</p></article>)}</div></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white"><DocumentationFrame dark className="grid gap-10 px-[var(--page-gutter)] py-[clamp(68px,7vw,100px)] min-[901px]:grid-cols-[1fr_0.8fr] md:px-[clamp(38px,5vw,68px)]"><div><DocumentationKicker>THE BOUNDARY</DocumentationKicker><h2 className={cn(documentationType.section, "mt-6")}>Extend how Skopos helps. Not who owns the truth.</h2></div><p className="m-0 self-end text-lg leading-[1.65] text-[var(--skopos-night-muted)]">Custom tools, rules, Skills, adapters, and services can contribute context, operations, and proof. They cannot create a second Task lifecycle, bypass project Guards, or declare their own Readiness.</p></DocumentationFrame></DocumentationSection>
  </article></SiteShell>;
}
