import Link from "next/link";
import type { ReactNode } from "react";
import { Icon } from "@/components/ui/icon";
import { cn } from "@/lib/utils";
import { SiteShell } from "@/patterns/site/site-shell";
import { docsLandingCopy, quickstartModes } from "./content";
import { DocumentationCopyBlock } from "./copy-block";
import { DocumentationFrame, DocumentationGrid, DocumentationKicker, DocumentationSection, DocumentationSectionHeading, documentationType } from "./documentation-layout";

function SmartLink({ href, children, className }: { href: string; children: ReactNode; className?: string }) { return href.startsWith("http") ? <a className={className} href={href} target="_blank" rel="noreferrer">{children}</a> : <Link className={className} href={href}>{children}</Link>; }
const action = "flex min-h-[52px] items-center justify-between gap-6 border border-[var(--skopos-ink)] px-[18px] text-[13px] font-bold";

export function DocsLandingScreen() {
  return <SiteShell><article className="bg-[var(--skopos-paper)]">
    <header><DocumentationSection><DocumentationFrame className="grid min-h-[clamp(620px,calc(100vh-64px),820px)] min-[901px]:grid-cols-[1.12fr_0.88fr]"><div className="flex flex-col items-start justify-center px-[var(--page-gutter)] py-[clamp(72px,8vw,112px)] md:px-[clamp(38px,5.5vw,78px)]"><h1 className={cn(documentationType.hero, "max-w-[790px]")}>{docsLandingCopy.title}</h1><p className="mt-[30px] max-w-[660px] text-[clamp(1rem,1.22vw,1.16rem)] leading-[1.64] text-[var(--skopos-muted)]">{docsLandingCopy.description}</p><Link className={cn(action, "mt-9 bg-[var(--skopos-ink)] text-white")} href="/docs/quickstart">Open the quickstart<Icon symbol="arrow_forward" size="sm" /></Link></div><DocumentationGrid className="grid grid-rows-[auto_repeat(4,1fr)] border-t border-[var(--skopos-rule-light)] min-[901px]:border-t-0 min-[901px]:border-l"><span className="border-b border-[var(--skopos-rule-light)] bg-[rgba(248,247,243,.93)] px-7 py-6 text-[11px] font-bold tracking-[0.12em] text-[#686868] uppercase">Start with your situation</span>{docsLandingCopy.startRoutes.map((route) => <Link key={route.number} className="grid grid-cols-[44px_1fr_auto] items-center gap-[18px] border-b border-[var(--skopos-rule-light)] bg-[rgba(248,247,243,.93)] px-7 py-6 last:border-b-0 hover:bg-white" href={route.href}><span className="font-mono text-xs">{route.number}</span><strong className="text-base leading-[1.25]">{route.title}</strong><Icon symbol="arrow_forward" size="sm" /></Link>)}</DocumentationGrid></DocumentationFrame></DocumentationSection></header>
    <div className="border-y border-[var(--skopos-rule-light)]"><DocumentationSection><DocumentationFrame className="grid md:grid-cols-3">{docsLandingCopy.summary.map((item, index) => <p key={item} className={cn("m-0 flex min-h-[72px] items-center gap-[18px] border-b border-[var(--skopos-rule-light)] px-[30px] py-6 text-sm font-semibold md:min-h-[90px] md:border-r md:border-b-0", index === docsLandingCopy.summary.length - 1 && "border-b-0 md:border-r-0")}><span className="font-mono text-[11px] text-[#7c7c7c]">{String(index + 1).padStart(2, "0")}</span>{item}</p>)}</DocumentationFrame></DocumentationSection></div>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white" aria-labelledby="docs-first-step-title"><DocumentationFrame dark className="grid min-[901px]:grid-cols-[0.88fr_1.12fr]"><div className="flex flex-col items-start justify-center px-[var(--page-gutter)] py-[clamp(70px,7vw,104px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>01</DocumentationKicker><h2 id="docs-first-step-title" className={cn(documentationType.section, "mt-[22px] max-w-[520px]")}>Your first step can be a conversation.</h2><p className="mt-[25px] max-w-[570px] text-base leading-[1.65] text-[var(--skopos-night-muted)]">You do not need to memorize the CLI before Skopos becomes useful. Tell the agent what kind of project this is and require it to preserve existing truth before changing anything.</p><Link className={cn(action, "mt-8 border-white bg-white text-[var(--skopos-ink)]")} href="/docs/quickstart">Follow every quickstart step<Icon symbol="arrow_forward" size="sm" /></Link></div><div className="border-t border-[var(--skopos-rule-dark)] p-[var(--page-gutter)] min-[901px]:border-t-0 min-[901px]:border-l md:p-[clamp(38px,5vw,68px)]"><DocumentationCopyBlock label="Existing project setup brief" value={quickstartModes.existing.prompt} kind="prompt" /></div></DocumentationFrame></DocumentationSection>
    <DocumentationSection aria-labelledby="docs-start-routes-title"><DocumentationFrame className="py-[clamp(70px,8vw,112px)]"><DocumentationSectionHeading number="02" id="docs-start-routes-title" title="Choose the path that matches your project." description="Each path starts with the outcome, shows what to say, explains what Skopos handles, and keeps exact commands close by." /><div className="grid border-t border-[var(--skopos-rule-light)] md:grid-cols-2">{docsLandingCopy.startRoutes.map((route, index) => <article key={route.number} className={cn("min-h-[260px] border-r border-b border-[var(--skopos-rule-light)] p-[clamp(30px,4vw,48px)]", index % 2 === 1 && "border-r-0", index >= 2 && "border-b-0")}><span className="font-mono text-[10px] text-[#777]">{route.number}</span><h3 className="mt-9 text-[clamp(1.7rem,2.5vw,2.5rem)] leading-none tracking-[-0.05em]">{route.title}</h3><p className="mt-5 leading-[1.6] text-[var(--skopos-muted)]">{route.description}</p><Link className="mt-7 flex items-center justify-between border-t border-[var(--skopos-rule-light)] pt-5 text-[13px] font-bold" href={route.href}>{route.action}<Icon symbol="arrow_forward" size="sm" /></Link></article>)}</div></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white" aria-labelledby="docs-workflows-title"><DocumentationFrame dark className="py-[clamp(70px,8vw,112px)]"><DocumentationSectionHeading dark number="03" id="docs-workflows-title" title="Work with your agent in plain English." description="Start with the result you want. Skopos supplies the project context, boundary, checks, and continuation state that the conversation alone cannot guarantee." /><div className="grid border-t border-[var(--skopos-rule-dark)] md:grid-cols-2 min-[1100px]:grid-cols-3">{docsLandingCopy.workflows.map((workflow, index) => <Link key={workflow.title} className={cn("grid min-h-[170px] grid-cols-[1fr_auto] content-between border-r border-b border-[var(--skopos-rule-dark)] p-7", index % 2 === 1 && "max-[1099px]:md:border-r-0", index >= 3 && "min-[1100px]:border-b-0", index >= 4 && "max-[1099px]:md:border-b-0", index % 3 === 2 && "min-[1100px]:border-r-0")} href={workflow.href}><span className="font-mono text-[9px] text-[#888]">{String(index + 1).padStart(2, "0")}</span><Icon symbol={workflow.icon} size="lg" /><strong className="self-end text-lg">{workflow.title}</strong><Icon className="self-end" symbol="arrow_forward" size="sm" /></Link>)}</div></DocumentationFrame></DocumentationSection>
    <DocumentationSection aria-labelledby="docs-library-title"><DocumentationFrame className="py-[clamp(70px,8vw,112px)]"><div className="px-[var(--page-gutter)] pb-[clamp(48px,6vw,72px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>04</DocumentationKicker><h2 id="docs-library-title" className={cn(documentationType.section, "mt-6")}>Go deeper only when you need to.</h2><p className="mt-5 max-w-[750px] leading-[1.65] text-[var(--skopos-muted)]">The public guide keeps common work approachable. Canonical Markdown remains available for exact architecture, configuration, and reference details.</p></div><div className="grid border-t border-[var(--skopos-rule-light)] md:grid-cols-2 min-[1100px]:grid-cols-5">{docsLandingCopy.library.map((group, index) => <article key={group.label} className={cn("min-h-[330px] border-r border-b border-[var(--skopos-rule-light)] p-7", index % 2 === 1 && "max-[1099px]:md:border-r-0", index >= 4 && "border-b-0", index === 4 && "border-r-0")}><h3 className="text-xl">{group.label}</h3><p className="mt-4 text-sm leading-[1.55] text-[var(--skopos-muted)]">{group.description}</p><ul className="mt-6 list-none border-t border-[var(--skopos-rule-light)] p-0">{group.links.map((link) => <li key={`${group.label}-${link.label}`} className="border-b border-[var(--skopos-rule-light)]"><SmartLink className="flex items-center justify-between gap-3 py-3 text-[13px] font-semibold" href={link.href}>{link.label}<Icon symbol={link.href.startsWith("http") ? "arrow_outward" : "arrow_forward"} size="sm" /></SmartLink></li>)}</ul></article>)}</div></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white"><DocumentationFrame dark className="grid min-h-[320px] items-center gap-12 px-[var(--page-gutter)] py-[clamp(56px,7vw,88px)] min-[901px]:grid-cols-[1fr_auto] md:px-[clamp(38px,5vw,68px)]"><div><h2 className={documentationType.section}>Begin with one repository and one honest review.</h2><p className="mt-5 max-w-[650px] leading-[1.65] text-[var(--skopos-night-muted)]">Installation is short. Trustworthy adoption begins by understanding the project you already have.</p></div><div className="flex flex-col gap-3"><Link className={cn(action, "border-white bg-white text-[var(--skopos-ink)]")} href="/docs/quickstart">Open the quickstart<Icon symbol="arrow_forward" size="sm" /></Link><a className={cn(action, "border-[var(--skopos-rule-dark)] text-white")} href="https://github.com/Croodo/skopos/blob/main/docs/00-start-here.md" target="_blank" rel="noreferrer">View source documentation<Icon symbol="arrow_outward" size="sm" /></a></div></DocumentationFrame></DocumentationSection>
  </article></SiteShell>;
}
