import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import { SiteShell } from "@/patterns/site/site-shell";
import { cn } from "@/lib/utils";
import { featureRequest, featureWorkflowOutcome } from "./feature-workflow-content";
import { FeatureWorkflowNavigator } from "./feature-workflow-navigator";
import { DocumentationBackLink, DocumentationFrame, DocumentationGrid, DocumentationKicker, DocumentationSection, DocumentationSectionHeading, documentationType } from "./documentation-layout";

export function FeatureWorkflowScreen() {
  return (
    <SiteShell>
      <article className="bg-[var(--skopos-paper)]">
        <header><DocumentationSection><DocumentationFrame className="grid min-h-[clamp(650px,calc(100vh-64px),820px)] min-[901px]:grid-cols-[1.08fr_0.92fr]"><div className="flex flex-col items-start justify-center px-[var(--page-gutter)] py-[clamp(70px,8vw,112px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationBackLink href="/docs">Documentation</DocumentationBackLink><DocumentationKicker className="mt-7">WORK WITH YOUR AGENT</DocumentationKicker><h1 className={cn(documentationType.hero, "mt-7 max-w-[760px]")}>Plan, build, and finish one real feature.</h1></div><DocumentationGrid className="flex min-h-[440px] flex-col items-start justify-center border-t border-[var(--skopos-rule-light)] px-[var(--page-gutter)] py-[clamp(70px,8vw,112px)] min-[901px]:min-h-0 min-[901px]:border-t-0 min-[901px]:border-l md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>You say</DocumentationKicker><blockquote className="mt-[34px] max-w-[560px] text-[clamp(2rem,3.4vw,3.55rem)] leading-[1.02] font-bold tracking-[-0.055em]">“{featureRequest}”</blockquote><p className="mt-[34px] max-w-[520px] text-[15px] leading-[1.65] text-[var(--skopos-muted)]">Skopos keeps the outcome coherent from the first discussion through proof, Memory review, and the next Session.</p></DocumentationGrid></DocumentationFrame></DocumentationSection></header>

        <div className="border-y border-[var(--skopos-rule-light)]" aria-label="Feature workflow summary"><DocumentationSection><DocumentationFrame className="grid md:grid-cols-3">{[["01", "One continuous example"], ["02", "Prompts and exact commands"], ["03", "Developer review at every stage"]].map(([number, text], index) => <p key={number} className={cn("m-0 flex min-h-[64px] items-center gap-[18px] border-b border-[var(--skopos-rule-light)] px-7 py-[22px] text-[13px] font-semibold md:min-h-[86px] md:border-r md:border-b-0", index === 2 && "border-b-0 md:border-r-0")}><span className="font-mono text-[10px] text-[#777]">{number}</span>{text}</p>)}</DocumentationFrame></DocumentationSection></div>

        <DocumentationSection aria-labelledby="feature-guide-workflow-title"><DocumentationFrame className="py-[clamp(72px,8vw,112px)]"><DocumentationSectionHeading number="THE COMPLETE LOOP" id="feature-guide-workflow-title" title="Talk normally. Keep every important step reviewable." description="Move through the seven stages below. The prompt establishes intent; the command path shows the same authority precisely." /><FeatureWorkflowNavigator /></DocumentationFrame></DocumentationSection>

        <DocumentationSection className="bg-[var(--skopos-night)] text-white" aria-labelledby="feature-guide-outcome-title"><DocumentationFrame dark className="grid min-[1001px]:grid-cols-[0.85fr_1.15fr]"><div className="flex flex-col justify-center px-[var(--page-gutter)] py-[clamp(70px,8vw,110px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>DONE MEANS</DocumentationKicker><h2 id="feature-guide-outcome-title" className={cn(documentationType.section, "mt-[26px]")}>The feature works, the proof is fresh, and the project remembers why.</h2></div><ul className="m-0 flex list-none flex-col justify-center border-t border-[var(--skopos-rule-dark)] p-0 min-[1001px]:border-t-0 min-[1001px]:border-l">{featureWorkflowOutcome.map((item, index) => <li key={item} className={cn("grid min-h-[100px] grid-cols-[34px_1fr] items-center gap-[18px] border-b border-[var(--skopos-rule-dark)] px-[34px] py-5 text-sm font-semibold", index === featureWorkflowOutcome.length - 1 && "border-b-0")}><Icon symbol="check_circle" size="sm" />{item}</li>)}</ul></DocumentationFrame></DocumentationSection>

        <DocumentationSection className="bg-[var(--skopos-night)] text-white"><DocumentationFrame dark className="grid min-h-[340px] items-center gap-[60px] border-t px-[var(--page-gutter)] py-[clamp(56px,7vw,88px)] min-[901px]:grid-cols-[1fr_auto] md:px-[clamp(38px,5vw,68px)]"><div><DocumentationKicker>NEXT GUIDE</DocumentationKicker><h2 className={cn(documentationType.section, "mt-[22px]")}>Continue the work in a fresh Session.</h2><p className="mt-5 max-w-[650px] leading-[1.65] text-[var(--skopos-night-muted)]">Learn how to move current intent and live project state without replaying or summarizing an entire old conversation.</p></div><Link className="flex min-h-[58px] w-full items-center justify-between gap-[22px] bg-white px-5 text-[13px] font-bold text-[var(--skopos-ink)] min-[901px]:w-auto min-[901px]:min-w-[290px]" href="/docs/workflows/continue-fresh-session">Continue in a fresh Session<Icon symbol="arrow_forward" size="sm" /></Link></DocumentationFrame></DocumentationSection>
      </article>
    </SiteShell>
  );
}
