"use client";

import { type KeyboardEvent, useEffect, useRef, useState } from "react";
import { DocumentationCopyBlock } from "./copy-block";
import { freshSessionStages, type FreshSessionStageId } from "./agent-work-content";
import { cn } from "@/lib/utils";
import { documentationType } from "./documentation-layout";

function isStage(value: string): value is FreshSessionStageId { return freshSessionStages.some((item) => item.id === value); }

export function FreshSessionNavigator() {
  const [selected, setSelected] = useState<FreshSessionStageId>("prepare");
  const refs = useRef<Array<HTMLButtonElement | null>>([]);
  const stage = freshSessionStages.find((item) => item.id === selected) ?? freshSessionStages[0];
  useEffect(() => { const sync = () => { const hash = window.location.hash.slice(1); if (isStage(hash)) setSelected(hash); }; sync(); window.addEventListener("hashchange", sync); return () => window.removeEventListener("hashchange", sync); }, []);
  const choose = (id: FreshSessionStageId) => { setSelected(id); window.history.replaceState(null, "", `#${id}`); };
  const onKeyDown = (event: KeyboardEvent<HTMLButtonElement>, index: number) => { if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return; event.preventDefault(); const last = freshSessionStages.length - 1; const nextIndex = event.key === "Home" ? 0 : event.key === "End" ? last : event.key === "ArrowRight" ? (index + 1) % freshSessionStages.length : (index - 1 + freshSessionStages.length) % freshSessionStages.length; choose(freshSessionStages[nextIndex].id); refs.current[nextIndex]?.focus(); };
  return <div className="border-y border-[var(--skopos-rule-light)]"><div className="grid grid-cols-2 border-b border-[var(--skopos-rule-light)] min-[901px]:grid-cols-6" role="tablist" aria-label="Fresh Session stages">{freshSessionStages.map((item, index) => <button key={item.id} ref={(node) => { refs.current[index] = node; }} id={`fresh-session-tab-${item.id}`} role="tab" type="button" aria-selected={selected === item.id} aria-controls="fresh-session-panel" tabIndex={selected === item.id ? 0 : -1} className={cn("flex min-h-[70px] items-center gap-3 border-r border-b border-[var(--skopos-rule-light)] bg-transparent px-[14px] py-[15px] text-left text-xs font-bold text-[#606060] [font-family:var(--font-sans)] even:border-r-0 min-[901px]:min-h-[80px] min-[901px]:border-b-0 min-[901px]:px-[18px] min-[901px]:even:border-r min-[901px]:last:border-r-0", index >= freshSessionStages.length - 2 && "border-b-0", selected === item.id && "bg-[var(--skopos-ink)] text-white")} onClick={() => choose(item.id)} onKeyDown={(event) => onKeyDown(event, index)}><span className={cn("font-mono text-[9px] text-[#777]", selected === item.id && "text-[#aaa]")}>{item.number}</span>{item.verb}</button>)}</div><section id="fresh-session-panel" role="tabpanel" aria-labelledby={`fresh-session-tab-${stage.id}`}><header className="grid min-h-[290px] items-end gap-[30px] border-b border-[var(--skopos-rule-light)] px-[var(--page-gutter)] py-[clamp(42px,5vw,64px)] min-[901px]:grid-cols-[1.1fr_0.9fr] min-[901px]:gap-[50px] md:px-[clamp(38px,5vw,68px)]"><div><span className="font-mono text-[10px] text-[#757575]">{stage.number} · {stage.verb}</span><h2 className={cn(documentationType.section, "mt-[25px]")}>{stage.title}</h2></div><p className="m-0 leading-[1.65] text-[var(--skopos-muted)]">{stage.description}</p></header><div className="grid bg-[var(--skopos-night)] min-[901px]:grid-cols-2 [&_.docs-copy-block]:border-0 [&_.docs-copy-block]:border-b [&_.docs-copy-block]:border-[var(--skopos-rule-dark)] [&_.docs-copy-block:last-child]:border-b-0 min-[901px]:[&_.docs-copy-block]:border-r min-[901px]:[&_.docs-copy-block]:border-b-0 min-[901px]:[&_.docs-copy-block:last-child]:border-r-0 [&_.docs-copy-block_blockquote]:min-h-[340px] [&_.docs-copy-block_ol]:min-h-[340px]"><DocumentationCopyBlock label="Say this to your agent" value={stage.prompt} kind="prompt" /><DocumentationCopyBlock label="Exact command path" value={stage.commands} kind="commands" /></div><footer className="grid min-h-[105px] grid-cols-1 items-center gap-2 bg-[var(--skopos-ink)] px-[var(--page-gutter)] py-6 text-white md:grid-cols-[150px_1fr] md:gap-6 md:px-[clamp(36px,4vw,52px)]"><span className="font-mono text-[10px] tracking-[0.09em] text-[#969696]">PROJECT TRUTH</span><strong className="max-w-[930px] text-[15px] leading-[1.55]">{stage.truth}</strong></footer></section></div>;
}
