import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import { SiteShell } from "@/patterns/site/site-shell";
import { cn } from "@/lib/utils";
import { hostDeliveryTruth } from "./agent-work-content";
import { DocumentationFrame, DocumentationGrid, DocumentationKicker, DocumentationSection, documentationType } from "./documentation-layout";
import { FreshSessionNavigator } from "./fresh-session-navigator";

export function FreshSessionScreen() {
  return <SiteShell><article className="bg-[var(--skopos-paper)]">
    <header><DocumentationSection><DocumentationFrame className="grid min-h-[clamp(620px,calc(100vh-64px),790px)] min-[901px]:grid-cols-[1.1fr_0.9fr]"><div className="flex flex-col items-start justify-center px-[var(--page-gutter)] py-[clamp(70px,8vw,112px)] md:px-[clamp(38px,5vw,68px)]"><Link className="quickstart-back" href="/docs/work-with-your-agent"><Icon symbol="arrow_back" size="sm" />Work with your agent</Link><h1 className={cn(documentationType.hero, "mt-9 max-w-[850px]")}>Move the work to a fresh Session—without starting over.</h1><p className="mt-[30px] max-w-[680px] text-[17px] leading-[1.65] text-[var(--skopos-muted)]">Carry the current intent and project state into a clean coding-agent conversation. Keep every step reviewable and never confuse a generated handoff with a delivered one.</p></div><DocumentationGrid className="flex min-h-[420px] flex-col justify-center border-t border-[var(--skopos-rule-light)] px-[var(--page-gutter)] py-[clamp(52px,6vw,82px)] min-[901px]:min-h-0 min-[901px]:border-t-0 min-[901px]:border-l md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>NOT THE SAME THING</DocumentationKicker>{[["Resume", "reopens the same host conversation."], ["Fresh Session", "creates a new host conversation and binds it to the Task."], ["Project truth", "remains in Skopos and the repository."]].map(([title, text]) => <p key={title} className="m-0 border-b border-[var(--skopos-rule-light)] py-[27px] leading-[1.55] text-[var(--skopos-muted)]"><strong className="mb-[5px] block text-[17px] text-[var(--skopos-ink)]">{title}</strong>{text}</p>)}</DocumentationGrid></DocumentationFrame></DocumentationSection></header>
    <DocumentationSection className="border-t border-[var(--skopos-rule-light)]" aria-labelledby="fresh-session-flow-title"><DocumentationFrame className="py-[clamp(72px,8vw,112px)]"><header className="px-[var(--page-gutter)] pb-[clamp(52px,6vw,76px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>THE HANDOFF</DocumentationKicker><h2 id="fresh-session-flow-title" className={cn(documentationType.section, "mt-[25px] max-w-[850px]")}>Six explicit steps. No invisible jump between them.</h2><p className="mt-[22px] max-w-[690px] leading-[1.65] text-[var(--skopos-muted)]">The original Session prepares and reviews the transfer. The receiving Session accepts current authority before continuing.</p></header><FreshSessionNavigator /></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="border-t border-[var(--skopos-rule-light)]" aria-labelledby="fresh-session-hosts-title"><DocumentationFrame className="py-[clamp(72px,8vw,112px)]"><header className="grid gap-7 px-[var(--page-gutter)] pb-[clamp(52px,6vw,76px)] md:grid-cols-[150px_1fr] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>HOST REALITY</DocumentationKicker><h2 id="fresh-session-hosts-title" className={cn(documentationType.section, "max-w-[850px] md:mt-0")}>Automation follows verified host capability.</h2></header><div className="grid border-t border-[var(--skopos-rule-light)] min-[901px]:grid-cols-3">{hostDeliveryTruth.map((host, index) => <article key={host.label} className={cn("min-h-[240px] border-b border-[var(--skopos-rule-light)] p-[clamp(32px,4vw,48px)] min-[901px]:min-h-[300px] min-[901px]:border-b-0 min-[901px]:border-r", index === hostDeliveryTruth.length - 1 && "border-b-0 min-[901px]:border-r-0")}><span className="font-mono text-[9px] tracking-[0.08em] text-[#757575] uppercase">{host.status}</span><h3 className="mt-[55px] text-[clamp(1.9rem,2.6vw,2.7rem)] tracking-[-0.05em]">{host.label}</h3><p className="mt-[22px] leading-[1.6] text-[var(--skopos-muted)]">{host.detail}</p></article>)}</div></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white"><DocumentationFrame dark className="grid min-[901px]:grid-cols-[0.9fr_1.1fr]"><div className="flex flex-col justify-center px-[var(--page-gutter)] py-[clamp(60px,7vw,92px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>WHEN VERIFICATION STOPS</DocumentationKicker><h2 className={cn(documentationType.section, "mt-[25px]")}>Refresh what changed. Never silently trim or guess.</h2></div><ul className="m-0 grid list-none grid-cols-1 border-t border-[var(--skopos-rule-dark)] p-0 sm:grid-cols-2 min-[901px]:border-t-0 min-[901px]:border-l">{[["Refreshable", "Rebuild the handoff around its preserved capsule."], ["Stale", "Inspect the Task-owned state before proceeding."], ["Conflicted", "Reconcile actions, mutations, claims, or contamination."], ["Invalid", "Reject the handoff. Sensitive values are redacted and over-budget prompts fail explicitly."]].map(([title, text], index) => <li key={title} className={cn("flex min-h-[135px] flex-col justify-center gap-3 border-b border-[var(--skopos-rule-dark)] px-[34px] py-7 sm:min-h-[170px] sm:border-r", index % 2 === 1 && "sm:border-r-0", index >= 2 && "sm:border-b-0", index === 3 && "border-b-0")}><strong>{title}</strong><span className="text-[13px] leading-[1.55] text-[var(--skopos-night-muted)]">{text}</span></li>)}</ul></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white"><DocumentationFrame dark className="flex min-h-[290px] flex-col items-start justify-between gap-[50px] border-t px-[var(--page-gutter)] py-[clamp(52px,6vw,76px)] min-[901px]:flex-row min-[901px]:items-center md:px-[clamp(38px,5vw,68px)]"><div><DocumentationKicker>NEXT GUIDE</DocumentationKicker><h2 className={cn(documentationType.section, "mt-[25px]")}>See the complete feature loop.</h2></div><Link className="flex min-h-[58px] w-full items-center justify-between gap-[22px] bg-white px-5 text-[13px] font-bold text-[var(--skopos-ink)] min-[901px]:w-auto min-[901px]:min-w-[290px]" href="/docs/workflows/plan-and-finish-feature">Plan and finish a feature<Icon symbol="arrow_forward" size="sm" /></Link></DocumentationFrame></DocumentationSection>
  </article></SiteShell>;
}
