import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import { cn } from "@/lib/utils";
import { SiteShell } from "@/patterns/site/site-shell";
import { DocumentationCopyBlock } from "./copy-block";
import { continueWorkPrompt, quickstartDoneWhen, quickstartProblems } from "./content";
import { DocumentationBackLink, DocumentationFrame, DocumentationKicker, DocumentationSection, DocumentationSectionHeading, documentationType } from "./documentation-layout";
import { QuickstartSwitcher } from "./quickstart-switcher";

export function QuickstartScreen() {
  const review = [["01", "Boundary", "Confirm the repository root, project mode, Scopes, and Memory roots."], ["02", "Truth", "Separate observed files and commands from inferences and open assumptions."], ["03", "Changes", "Review AGENTS.md, configuration, docs routing, and ignore rules before committing."], ["04", "Adoption", "Require an exact proposal before material documentation restructuring."]];
  return <SiteShell><article className="bg-[var(--skopos-paper)]">
    <header><DocumentationSection><DocumentationFrame className="grid min-h-[clamp(560px,calc(100vh-64px),740px)] items-center min-[901px]:grid-cols-[1.1fr_0.9fr]"><div className="px-[var(--page-gutter)] py-[clamp(70px,8vw,112px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationBackLink href="/docs">Documentation</DocumentationBackLink><h1 className={cn(documentationType.hero, "mt-9 max-w-[780px]")}>Get one repository ready for coding agents.</h1></div><p className="m-0 border-t border-[var(--skopos-rule-light)] px-[var(--page-gutter)] py-[clamp(56px,7vw,96px)] text-[clamp(1.35rem,2.3vw,2.2rem)] leading-[1.35] tracking-[-0.035em] text-[var(--skopos-muted)] min-[901px]:border-t-0 min-[901px]:border-l md:px-[clamp(38px,5vw,68px)]">Install Skopos, tell your agent how to approach the project, review what it found, and finish with a project state that can guide the next Session.</p></DocumentationFrame></DocumentationSection></header>
    <div className="border-y border-[var(--skopos-rule-light)]"><DocumentationSection><DocumentationFrame className="grid grid-cols-2 min-[700px]:grid-cols-5">{[["01", "Choose"], ["02", "Install"], ["03", "Discuss"], ["04", "Review"], ["05", "Verify"]].map(([number, label], index) => <p key={number} className={cn("m-0 flex min-h-[68px] items-center gap-3 border-r border-b border-[var(--skopos-rule-light)] px-5 text-[13px] font-bold min-[700px]:border-b-0", index % 2 === 1 && "max-[699px]:border-r-0", index >= 4 && "border-b-0", index === 4 && "border-r-0")}><span className="font-mono text-[10px] text-[#777]">{number}</span>{label}</p>)}</DocumentationFrame></DocumentationSection></div>
    <DocumentationSection aria-labelledby="quickstart-path-title"><DocumentationFrame className="py-[clamp(70px,8vw,112px)]"><DocumentationSectionHeading number="01" id="quickstart-path-title" title="Choose the project you are bringing." description="The safe setup path depends on whether the repository already contains project truth." /><QuickstartSwitcher /></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="border-t border-[var(--skopos-rule-light)]" aria-labelledby="quickstart-review-title"><DocumentationFrame className="grid min-[901px]:grid-cols-[0.9fr_1.1fr]"><div className="px-[var(--page-gutter)] py-[clamp(68px,7vw,100px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>02</DocumentationKicker><h2 id="quickstart-review-title" className={cn(documentationType.section, "mt-6")}>Review before broad agent work.</h2><p className="mt-6 leading-[1.65] text-[var(--skopos-muted)]">Initialization is not a declaration that every detected fact is correct. Treat generated tracked files like onboarding changes: inspect them, adjust real project choices, then commit only what matches the repository.</p></div><ol className="m-0 grid list-none border-t border-[var(--skopos-rule-light)] p-0 sm:grid-cols-2 min-[901px]:border-t-0 min-[901px]:border-l">{review.map(([number, title, text], index) => <li key={title} className={cn("min-h-[190px] border-r border-b border-[var(--skopos-rule-light)] p-8", index % 2 === 1 && "border-r-0", index >= 2 && "border-b-0")}><span className="font-mono text-[10px] text-[#777]">{number}</span><strong className="mt-8 block text-xl">{title}</strong><p className="mt-3 text-sm leading-[1.6] text-[var(--skopos-muted)]">{text}</p></li>)}</ol></DocumentationFrame></DocumentationSection>
    <DocumentationSection id="continue-work" className="border-t border-[var(--skopos-rule-light)]" aria-labelledby="quickstart-continue-title"><DocumentationFrame className="grid min-[901px]:grid-cols-2"><div className="px-[var(--page-gutter)] py-[clamp(68px,7vw,100px)] md:px-[clamp(38px,5vw,68px)]"><DocumentationKicker>03</DocumentationKicker><h2 id="quickstart-continue-title" className={cn(documentationType.section, "mt-6")}>Return without replaying the old chat.</h2><p className="mt-6 leading-[1.65] text-[var(--skopos-muted)]">Once the project is set up, a new Session can recover the active work, relevant Memory, remaining proof, and next safe action from the repository.</p><div className="mt-8"><DocumentationCopyBlock label="Run it yourself" value={["npx skopos session context . --actor <id> --json", "npx skopos work next . --actor <id> --json"]} kind="commands" /></div></div><div className="border-t border-[var(--skopos-rule-light)] p-[var(--page-gutter)] min-[901px]:border-t-0 min-[901px]:border-l md:p-[clamp(38px,5vw,68px)]"><DocumentationCopyBlock label="Say this to your agent" value={continueWorkPrompt} kind="prompt" /></div></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white" aria-labelledby="quickstart-done-title"><DocumentationFrame dark className="py-[clamp(70px,8vw,112px)]"><DocumentationSectionHeading dark number="04" id="quickstart-done-title" title="You are done when the project can explain itself." description="Setup success is observable. It is not just the absence of a CLI error." /><ul className="m-0 grid list-none border-t border-[var(--skopos-rule-dark)] p-0 md:grid-cols-2">{quickstartDoneWhen.map((item, index) => <li key={item} className={cn("grid min-h-[110px] grid-cols-[26px_32px_1fr] items-center gap-3 border-r border-b border-[var(--skopos-rule-dark)] px-8 py-5 text-sm leading-[1.55]", index % 2 === 1 && "border-r-0", index >= 2 && "border-b-0")}><Icon symbol="check_circle" size="sm" /><span className="font-mono text-[10px] text-[#888]">{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ul></DocumentationFrame></DocumentationSection>
    <DocumentationSection aria-labelledby="quickstart-problems-title"><DocumentationFrame className="py-[clamp(70px,8vw,112px)]"><DocumentationSectionHeading number="05" id="quickstart-problems-title" title="If setup does not look right, stop safely." description="Skopos should make the recovery path explicit instead of encouraging you to force a questionable setup through." /><div className="grid border-t border-[var(--skopos-rule-light)] md:grid-cols-2">{quickstartProblems.map((problem, index) => <article key={problem.title} className={cn("min-h-[250px] border-r border-b border-[var(--skopos-rule-light)] p-[clamp(30px,4vw,48px)]", index % 2 === 1 && "border-r-0", index >= 2 && "border-b-0")}><span className="font-mono text-[10px] text-[#777]">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-9 text-[clamp(1.7rem,2.4vw,2.35rem)] leading-none tracking-[-0.045em]">{problem.title}</h3><p className="mt-5 leading-[1.6] text-[var(--skopos-muted)]">{problem.recovery}</p></article>)}</div></DocumentationFrame></DocumentationSection>
    <DocumentationSection className="bg-[var(--skopos-night)] text-white"><DocumentationFrame dark className="grid min-h-[330px] items-center gap-12 px-[var(--page-gutter)] py-[clamp(56px,7vw,88px)] min-[901px]:grid-cols-[1fr_auto] md:px-[clamp(38px,5vw,68px)]"><div><h2 className={documentationType.section}>Next, use Skopos on one real feature.</h2><p className="mt-5 max-w-[650px] leading-[1.65] text-[var(--skopos-night-muted)]">Let the agent recover the relevant project context, clarify the outcome, bind the work, and prove it against the checks your project owns.</p></div><div className="flex flex-col gap-3"><NextLink href="/docs/workflows/plan-and-finish-feature">Plan and build a feature</NextLink><NextLink href="/how-it-works" dark>See the complete loop</NextLink></div></DocumentationFrame></DocumentationSection>
  </article></SiteShell>;
}

function NextLink({ href, children, dark = false }: { href: string; children: string; dark?: boolean }) { return <Link className={cn("flex min-h-14 min-w-[280px] items-center justify-between gap-5 px-5 text-[13px] font-bold", dark ? "border border-[var(--skopos-rule-dark)] text-white" : "bg-white text-[var(--skopos-ink)]")} href={href}>{children}<Icon symbol="arrow_forward" size="sm" /></Link>; }
