"use client";
import { type KeyboardEvent, useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { resolveFragmentId, revealFragmentTarget } from "@/lib/fragment-navigation";
import { DocumentationCopyBlock } from "./copy-block";
import { quickstartModes } from "./content";
import { documentationType } from "./documentation-layout";
type QuickstartMode = keyof typeof quickstartModes;
const quickstartModeIds = Object.values(quickstartModes).map((mode) => mode.id);

export function QuickstartSwitcher() {
  const [mode, setMode] = useState<QuickstartMode>("existing"); const existingRef = useRef<HTMLButtonElement>(null); const greenfieldRef = useRef<HTMLButtonElement>(null); const content = quickstartModes[mode];
  useEffect(() => { const sync = () => { const fragmentId = resolveFragmentId(window.location.hash, quickstartModeIds); if (!fragmentId) return; const nextMode = fragmentId === quickstartModes.greenfield.id ? "greenfield" : "existing"; setMode(nextMode); window.requestAnimationFrame(() => revealFragmentTarget(fragmentId)); }; sync(); window.addEventListener("hashchange", sync); return () => window.removeEventListener("hashchange", sync); }, []);
  const select = (next: QuickstartMode) => { setMode(next); window.history.replaceState(null, "", `#${quickstartModes[next].id}`); };
  const onKeyDown = (event: KeyboardEvent<HTMLButtonElement>, current: QuickstartMode) => { if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return; event.preventDefault(); const next = event.key === "Home" ? "existing" : event.key === "End" ? "greenfield" : current === "existing" ? "greenfield" : "existing"; select(next); (next === "existing" ? existingRef : greenfieldRef).current?.focus(); };
  return <div className="border-y border-[var(--skopos-rule-light)]"><div className="grid grid-cols-2 border-b border-[var(--skopos-rule-light)]" role="tablist" aria-label="Choose a project starting point">{(Object.keys(quickstartModes) as QuickstartMode[]).map((key) => <button key={key} ref={key === "existing" ? existingRef : greenfieldRef} id={quickstartModes[key].id} type="button" role="tab" aria-selected={mode === key} aria-controls="quickstart-panel" tabIndex={mode === key ? 0 : -1} className={cn("scroll-mt-20 min-h-[70px] border-0 border-r border-[var(--skopos-rule-light)] bg-transparent px-5 text-sm font-bold text-[#606060] last:border-r-0", mode === key && "bg-[var(--skopos-ink)] text-white")} onClick={() => select(key)} onKeyDown={(event) => onKeyDown(event, key)}>{quickstartModes[key].tabLabel}</button>)}</div><div id="quickstart-panel" role="tabpanel" aria-labelledby={quickstartModes[mode].id} className="grid min-[901px]:grid-cols-2"><div className="px-[var(--page-gutter)] py-[clamp(48px,6vw,72px)] md:px-[clamp(38px,5vw,68px)]"><h2 className={documentationType.section}>{content.title}</h2><p className="mt-5 leading-[1.65] text-[var(--skopos-muted)]">{content.description}</p></div><div className="border-t border-[var(--skopos-rule-light)] bg-[var(--skopos-night)] p-0 min-[901px]:border-t-0 min-[901px]:border-l"><DocumentationCopyBlock label="Say this to your agent" value={content.prompt} kind="prompt" /><DocumentationCopyBlock label="Run it yourself" value={content.commands} kind="commands" /></div><div className="border-t border-[var(--skopos-rule-light)] px-[var(--page-gutter)] py-10 min-[901px]:col-span-2 md:px-[clamp(38px,5vw,68px)]"><span className="font-mono text-[10px] font-bold tracking-[0.1em] text-[#777] uppercase">What to review</span><ul className="mt-5 grid list-none gap-0 border-t border-[var(--skopos-rule-light)] p-0 md:grid-cols-2">{content.review.map((item) => <li key={item} className="border-b border-[var(--skopos-rule-light)] py-4 pr-5 text-sm text-[var(--skopos-muted)]">{item}</li>)}</ul></div></div></div>;
}
